/* DO NOT EDIT THIS FILE - it is machine generated */
#include <termios.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <string.h>
#include <jni.h>
#include "android/log.h"
#include <stdio.h>
#include <stdlib.h>
//frank for boruan 2013-4-8
#ifdef __cplusplus
extern "C" {
#endif

	/*
	 *判断是否已经开启
	 */
	int isopen();
    /*
	 *打开FM1702
	 */
	int openFM1702();

     /*
	 *关闭FM1702
	 */
    int closeFM1702();
     /*
	 *选择卡类型
	 */
    int selectFM1702();
    /*
	 *读卡类型
	 */
    int readcard();


#ifdef __cplusplus
}
#endif

