/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_frankhujiyun_android_config_DownloadConfiger */

#ifndef _Included_com_frankhujiyun_android_config_DownloadConfiger
#define _Included_com_frankhujiyun_android_config_DownloadConfiger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_frankhujiyun_android_config_DownloadConfiger
 * Method:    GetconfigArray
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_frankhujiyun_android_config_DownloadConfiger_GetconfigArray
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
